"""init

Revision ID: 0001
Revises:
Create Date: 2026-07-30 11:25:03.876802

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS "auth"')
    op.execute('CREATE SCHEMA IF NOT EXISTS "frontiers"')
    op.create_table(
        'users',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('login', sa.String(), nullable=False),
        sa.Column('password_hash', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema='auth',
    )
    op.create_index(op.f('ix_auth_users_login'), 'users', ['login'], unique=True, schema='auth')
    op.create_table(
        'actions',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column(
            'type', sa.Enum('skill', 'buff', 'debuff', 'heal', name='actions_type', native_enum=False), nullable=False
        ),
        sa.PrimaryKeyConstraint('id'),
        schema='frontiers',
    )
    op.create_table(
        'characteristics',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('value', sa.Integer(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        schema='frontiers',
    )
    op.create_table(
        'fights',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column(
            'status',
            sa.Enum(
                'started', 'finished', 'interrupted', 'in_progress', 'canceled', name='fight_status', native_enum=False
            ),
            nullable=False,
        ),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('winner_side', sa.Enum('team_a', 'team_b', name='fight_side', native_enum=False), nullable=True),
        sa.Column('title', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema='frontiers',
    )
    op.create_table(
        'mobs',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema='frontiers',
    )
    op.create_index(op.f('ix_frontiers_mobs_title'), 'mobs', ['title'], unique=False, schema='frontiers')
    op.create_table(
        'characteristics_actions',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('characteristic_id', sa.Uuid(), nullable=False),
        sa.Column('action_id', sa.Uuid(), nullable=False),
        sa.Column('affect', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['action_id'],
            ['frontiers.actions.id'],
        ),
        sa.ForeignKeyConstraint(
            ['characteristic_id'],
            ['frontiers.characteristics.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('characteristic_id', 'action_id', name='uq_characteristics_actions_pair'),
        schema='frontiers',
    )
    op.create_index(
        op.f('ix_frontiers_characteristics_actions_action_id'),
        'characteristics_actions',
        ['action_id'],
        unique=False,
        schema='frontiers',
    )
    op.create_index(
        op.f('ix_frontiers_characteristics_actions_characteristic_id'),
        'characteristics_actions',
        ['characteristic_id'],
        unique=False,
        schema='frontiers',
    )
    op.create_table(
        'characters',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('account_id', sa.Uuid(), nullable=False),
        sa.Column('nickname', sa.String(), nullable=False),
        sa.Column('character_class', sa.Enum('adventurer', name='character_class', native_enum=False), nullable=False),
        sa.ForeignKeyConstraint(
            ['account_id'],
            ['auth.users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        schema='frontiers',
    )
    op.create_index(
        op.f('ix_frontiers_characters_account_id'), 'characters', ['account_id'], unique=True, schema='frontiers'
    )
    op.create_index(
        op.f('ix_frontiers_characters_nickname'), 'characters', ['nickname'], unique=True, schema='frontiers'
    )
    op.create_table(
        'sessions',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('account_id', sa.Uuid(), nullable=False),
        sa.Column('active_character_id', sa.Uuid(), nullable=True),
        sa.Column('refresh_token_hash', sa.String(), nullable=False),
        sa.Column('ip_address', sa.String(), nullable=True),
        sa.Column('user_agent', sa.Text(), nullable=True),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ['account_id'],
            ['auth.users.id'],
        ),
        sa.ForeignKeyConstraint(
            ['active_character_id'],
            ['frontiers.characters.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        schema='auth',
    )
    op.create_index(op.f('ix_auth_sessions_account_id'), 'sessions', ['account_id'], unique=False, schema='auth')
    op.create_index(
        op.f('ix_auth_sessions_active_character_id'), 'sessions', ['active_character_id'], unique=False, schema='auth'
    )
    op.create_index(
        op.f('ix_auth_sessions_refresh_token_hash'), 'sessions', ['refresh_token_hash'], unique=True, schema='auth'
    )
    op.create_table(
        'fight_participants',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('fight_id', sa.Uuid(), nullable=False),
        sa.Column('character_id', sa.Uuid(), nullable=True),
        sa.Column('mob_id', sa.Uuid(), nullable=True),
        sa.Column('side', sa.Enum('team_a', 'team_b', name='fight_side', native_enum=False), nullable=False),
        sa.CheckConstraint(
            '(character_id IS NOT NULL) <> (mob_id IS NOT NULL)', name='ck_fight_participant_exactly_one_actor'
        ),
        sa.ForeignKeyConstraint(
            ['character_id'],
            ['frontiers.characters.id'],
        ),
        sa.ForeignKeyConstraint(
            ['fight_id'],
            ['frontiers.fights.id'],
        ),
        sa.ForeignKeyConstraint(
            ['mob_id'],
            ['frontiers.mobs.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        schema='frontiers',
    )
    op.create_index(
        op.f('ix_frontiers_fight_participants_fight_id'),
        'fight_participants',
        ['fight_id'],
        unique=False,
        schema='frontiers',
    )
    op.create_table(
        'fight_actions',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('fight_id', sa.Uuid(), nullable=False),
        sa.Column('action_id', sa.Uuid(), nullable=False),
        sa.Column('initiator_participant_id', sa.Uuid(), nullable=False),
        sa.Column('target_participant_id', sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ['action_id'],
            ['frontiers.actions.id'],
        ),
        sa.ForeignKeyConstraint(
            ['fight_id'],
            ['frontiers.fights.id'],
        ),
        sa.ForeignKeyConstraint(
            ['initiator_participant_id'],
            ['frontiers.fight_participants.id'],
        ),
        sa.ForeignKeyConstraint(
            ['target_participant_id'],
            ['frontiers.fight_participants.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        schema='frontiers',
    )
    op.create_index(
        op.f('ix_frontiers_fight_actions_fight_id'), 'fight_actions', ['fight_id'], unique=False, schema='frontiers'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute('DROP SCHEMA "auth" CASCADE')
    op.execute('DROP SCHEMA "frontiers" CASCADE')
